//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiraTaxi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingShareApply
    {
        public int BookingShareID { get; set; }
        public int PassengerID { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public bool IsAuthorized { get; set; }
    
        public virtual BookingShare BookingShare { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
