//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiraTaxi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingShare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingShare()
        {
            this.BookingShareApplies = new HashSet<BookingShareApply>();
        }
    
        public int BookingShareID { get; set; }
        public Nullable<int> PassengerID { get; set; }
        public string BookingType { get; set; }
        public string VehicalType { get; set; }
        public string PickupPoint { get; set; }
        public string DestinationPoint { get; set; }
        public Nullable<System.TimeSpan> PickupTime { get; set; }
        public Nullable<System.TimeSpan> DropTime { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<System.DateTime> ShareDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> DriverTip { get; set; }
        public Nullable<decimal> nWayPaid { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingShareApply> BookingShareApplies { get; set; }
    }
}
