//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiraTaxi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverRating
    {
        public int DriverRatingID { get; set; }
        public int DriverID { get; set; }
        public string MemberID { get; set; }
        public int Rating { get; set; }
        public System.DateTime CrDate { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
