//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiraTaxi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverFareOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DriverFareOffer()
        {
            this.OfferApplies = new HashSet<OfferApply>();
        }
    
        public int DriverFareOfferID { get; set; }
        public int DriverID { get; set; }
        public System.DateTime OfferFrom { get; set; }
        public System.DateTime OfferTo { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public bool Status { get; set; }
        public string UserName { get; set; }
        public decimal Fare { get; set; }
    
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferApply> OfferApplies { get; set; }
    }
}
