//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiraTaxi.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LiraTaxiDBEntities : DbContext
    {
        public LiraTaxiDBEntities()
            : base("name=LiraTaxiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BookingApply> BookingApplies { get; set; }
        public virtual DbSet<BookingShare> BookingShares { get; set; }
        public virtual DbSet<BookingShareApply> BookingShareApplies { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<DriverCreditCard> DriverCreditCards { get; set; }
        public virtual DbSet<DriverFareOffer> DriverFareOffers { get; set; }
        public virtual DbSet<DriverNWaySale> DriverNWaySales { get; set; }
        public virtual DbSet<DriverRating> DriverRatings { get; set; }
        public virtual DbSet<OfferApply> OfferApplies { get; set; }
        public virtual DbSet<PaneltyMaster> PaneltyMasters { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<PassengerCreditCard> PassengerCreditCards { get; set; }
        public virtual DbSet<PassengerNWaySale> PassengerNWaySales { get; set; }
        public virtual DbSet<PassengerRating> PassengerRatings { get; set; }
        public virtual DbSet<StoreManager> StoreManagers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
