//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiraTaxi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferApply
    {
        public int OfferApplyID { get; set; }
        public string UserName { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public int DriverFareOfferID { get; set; }
    
        public virtual DriverFareOffer DriverFareOffer { get; set; }
    }
}
