//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiraTaxi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaneltyMaster
    {
        public int PaneltyMasterID { get; set; }
        public string PaneltyType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
    }
}
