//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiraTaxi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerCreditCard
    {
        public int PassengerCreditCard1 { get; set; }
        public int PassengerID { get; set; }
        public string CardType { get; set; }
        public string CardNo { get; set; }
        public string ExpiryDate { get; set; }
        public string NameOnCard { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    
        public virtual Passenger Passenger { get; set; }
    }
}
