//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiraTaxi.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerRating
    {
        public int PassengerRatignID { get; set; }
        public int PassengerID { get; set; }
        public string UserName { get; set; }
        public int Rating { get; set; }
        public System.DateTime CrDate { get; set; }
    }
}
